# Generated by Django 5.0.1 on 2024-01-31 14:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0002_alter_customuser_data_registro_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="ultimo_login",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
