# Generated by Django 5.0.1 on 2024-02-07 13:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0003_alter_customuser_ultimo_login"),
    ]

    operations = [
        migrations.CreateModel(
            name="Local",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=100)),
                ("slug", models.CharField(max_length=155)),
            ],
        ),
        migrations.CreateModel(
            name="Material",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=100)),
                ("slug", models.CharField(max_length=155)),
            ],
        ),
        migrations.CreateModel(
            name="Emprestimo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("data_emprestimo", models.DateTimeField()),
                ("data_recebimento", models.DateTimeField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("S", "Solicitado"),
                            ("R", "Recusado"),
                            ("E", "Emprestado"),
                            ("ES", "Entregue com sucesso"),
                            ("EP", "Entregue com prejuízo"),
                            ("EA", "Entregue com atraso"),
                            ("EPA", "Entregue com prejuízo e atraso"),
                        ],
                        default="S",
                        max_length=3,
                    ),
                ),
                (
                    "tipo",
                    models.CharField(
                        choices=[("L", "Local"), ("M", "Material"), ("A", "Ambos")],
                        max_length=1,
                    ),
                ),
                (
                    "fk_comodatario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="emprestimo_como",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "fk_funcionario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="emprestimo_func",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "fk_local",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="api.local"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="EmprestimoLocal",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("recebido", models.BooleanField(default=False)),
                (
                    "fk_emprestimo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="api.emprestimo"
                    ),
                ),
                (
                    "fk_material",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="api.material"
                    ),
                ),
            ],
            options={
                "unique_together": {("fk_emprestimo", "fk_material")},
            },
        ),
        migrations.AddField(
            model_name="emprestimo",
            name="mk_emprestimo_material",
            field=models.ManyToManyField(
                through="api.EmprestimoLocal", to="api.material"
            ),
        ),
        migrations.CreateModel(
            name="Multa",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("motivo", models.CharField(max_length=255)),
                ("valor", models.FloatField()),
                ("data_registro", models.DateTimeField()),
                ("data_pagamento", models.DateTimeField()),
                (
                    "fk_emprestimo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="api.emprestimo"
                    ),
                ),
            ],
        ),
    ]
