# Generated by Django 5.0.1 on 2024-02-07 13:07

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0004_local_material_emprestimo_emprestimolocal_and_more"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="EmprestimoLocal",
            new_name="EmprestimoMaterial",
        ),
    ]
